#!/bin/sh
# Build the playground's wasm module from an extracted CompCert tree.
#   usage: build.sh <compcert-dir> <out-dir>
# Expects CompCert to be configured and `make extraction` to have run.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
cc=$1
out=$2
cd "$cc"

# Release-tarball mode: don't turn warnings into errors (our patches leave
# a few unused values behind).
rm -rf .git

# --- Patches so that the driver can run without a filesystem or argv ---

# Commandline: expose the array parser so we can parse options from JS.
grep -q 'val parse_array' lib/Commandline.mli || cat >> lib/Commandline.mli <<'EOT'

val parse_array: (pattern * action) list -> string array -> int -> int -> unit
(** [parse_array actions argv first last] parses [argv.(first..last)]. *)
EOT

# Readconfig: read the configuration from a string instead of a file.
perl -0pi -e 's/let read_config_file filename =/let read_config_string filename s =
  let lexbuf = Lexing.from_string s in
  Lexing.(lexbuf.lex_start_p <- {lexbuf.lex_start_p with pos_fname = filename});
  Hashtbl.clear key_val_tbl;
  begline lexbuf

let read_config_file filename =/' lib/Readconfig.mll
cat >> lib/Readconfig.mli <<'EOT'

val read_config_string: string -> string -> unit
EOT

make compcert.ini

# Configuration: embed compcert.ini instead of looking for it next to the
# executable.
{
  echo '(* Generated by the playground build: contents of compcert.ini *)'
  printf 'let contents = {ini|'
  cat compcert.ini
  echo '|ini}'
} > driver/CompcertIni.ml
perl -0pi -e 's/let ini_file_name =.*?\n(let get_config key =)/let ini_file_name = "compcert.ini"
let ini_dir = "."
let _ = Readconfig.read_config_string ini_file_name CompcertIni.contents

$1/s' driver/Configuration.ml

# Clflags is a flat list of option refs; generate a module that can put
# them all back to their initial values between two compilations.
{
  echo '(* Generated by the playground build: resets every Clflags option. *)'
  echo 'let snap r = let v = !r in fun () -> r := v'
  echo 'let restore ='
  echo '  let saved = ['
  sed -n 's/^let \([a-zA-Z_0-9]*\) *=.*/    snap Clflags.\1;/p' driver/Clflags.ml
  echo '  ] in'
  echo '  fun () -> List.iter (fun f -> f ()) saved'
} > driver/PlaygroundFlags.ml

# Printers and exporters: route the lists of global definitions through
# PlaygroundFilter so that the playground can hide declarations that do not
# come from the user's file.  Each substitution must apply exactly as often
# as expected, so that an upstream change breaks the build instead of
# silently disabling the filter.
patch_count() { # <file> <expected count> <perl substitution>
  perl -0pi -e "\$n = ($3); END { die \"$1: expected $2 substitution(s), got \$n\\n\" unless \$n == $2 }" "$1"
}
patch_count cparser/Cprint.ml 1 's/List\.iter \(globdecl pp\) prog;/List.iter (globdecl pp) (PlaygroundFilter.globdecls prog);/g'
patch_count cfrontend/PrintCsyntax.ml 2 's/\bprog\.Ctypes\.prog_defs\b/(PlaygroundFilter.defs prog.Ctypes.prog_defs)/g'
patch_count cfrontend/PrintClight.ml 2 's/\bprog\.prog_defs\b/(PlaygroundFilter.defs prog.prog_defs)/g'
for f in backend/PrintCminor.ml backend/PrintRTL.ml backend/PrintLTL.ml backend/PrintMach.ml; do
  patch_count "$f" 1 's/\bprog\.prog_defs\b/(PlaygroundFilter.defs prog.prog_defs)/g'
done
patch_count backend/PrintAsm.ml 1 's/\bp\.prog_defs\b/(PlaygroundFilter.defs p.prog_defs)/g'
for f in export/ExportCsyntax.ml export/ExportClight.ml; do
  patch_count "$f" 2 's/(List\.iter \(print_globdef p\)|print_list print_ident_globdef p) prog\.Ctypes\.prog_defs/$1 (PlaygroundFilter.defs prog.Ctypes.prog_defs)/g'
  patch_count "$f" 1 's/print_list ident p prog\.Ctypes\.prog_public/print_list ident p (PlaygroundFilter.idents prog.Ctypes.prog_public)/g'
done
patch_count export/ExportBase.ml 1 's/\(fun \(id, name\) ->\n      try/(fun (id, name) ->\n      if not (PlaygroundFilter.hidden id) then\n      try/g'

cp "$here/PlaygroundFilter.ml" "$here/PlaygroundCore.ml" driver/

# --- Build ---

make tools/modorder driver/Version.ml
make -f Makefile.extr depend
objs=$(tools/modorder .depend.extr driver/PlaygroundCore.cmx | sed 's/\.cmx/.cmo/g')
make -f Makefile.extr -j"$(nproc)" $objs

includes="-I extraction -I lib -I common -I x86 -I backend -I cfrontend -I cparser -I driver -I export -I debug"
ocamlfind ocamlc -g -package js_of_ocaml $includes \
  -c "$here/playground_js.ml" -o driver/playground_js.cmo
ocamlfind ocamlc -g -package js_of_ocaml,menhirLib,str,unix -linkpkg \
  $objs driver/playground_js.cmo -o playground.byte

mkdir -p "$out"
wasm_of_ocaml compile --opt 3 playground.byte -o "$out/compcert.js"

# The wasm_of_ocaml loader only has a filesystem under Node.  In the
# browser, let it use an in-memory fs provided by the worker
# (globalThis.__wasm_of_ocaml_fs), and load the .wasm files relative to
# globalThis.__wasm_of_ocaml_base rather than the current script.
perl -pi -e '
  $n += s/(\w+)=(\w+)&&require\("node:fs"\)/$1=$2?require("node:fs"):globalThis.__wasm_of_ocaml_fs/;
  $m += s/"src":"compcert\.assets"/"src":(globalThis.__wasm_of_ocaml_base||"")+"compcert.assets"/;
  END { die "loader patch failed ($n, $m)\n" unless $n == 1 && $m == 1 }
' "$out/compcert.js"
ls -la "$out" "$out/compcert.assets"
