export type ViewId =
  | 'preprocessed'
  | 'parsed'
  | 'compcert_c'
  | 'clight'
  | 'cminor'
  | 'rtl'
  | 'ltl'
  | 'mach'
  | 'asm'
  | 'rocq';

export type View = {
  id: ViewId;
  label: string;
  language: string;
  description: string;
  /** Extension used when downloading. */
  ext: string;
};

export const VIEWS: View[] = [
  {
    id: 'preprocessed', label: 'Preprocessed', language: 'c', ext: 'i',
    description: 'Output of the C preprocessor (mcpp), as fed to CompCert.',
  },
  {
    id: 'parsed', label: 'Parsed C', language: 'c', ext: 'parsed.c',
    description: 'C after parsing and elaboration: the simplified C AST (-dparse).',
  },
  {
    id: 'compcert_c', label: 'CompCert C', language: 'c', ext: 'compcert.c',
    description: 'The CompCert C language, where expressions may have side effects (-dc).',
  },
  {
    id: 'clight', label: 'Clight', language: 'c', ext: 'light.c',
    description: 'Clight: side-effect-free expressions, with temporaries $N (-dclight).',
  },
  {
    id: 'cminor', label: 'Cminor', language: 'compcert-ir', ext: 'cm',
    description: 'Cminor: explicit stack allocation, no types on expressions (-dcminor).',
  },
  {
    id: 'rtl', label: 'RTL', language: 'compcert-ir', ext: 'rtl',
    description: 'Register transfer language: a CFG over pseudo-registers, before and after each optimization (-drtl).',
  },
  {
    id: 'ltl', label: 'LTL', language: 'compcert-ir', ext: 'ltl',
    description: 'Location transfer language: RTL after register allocation (-dltl).',
  },
  {
    id: 'mach', label: 'Mach', language: 'compcert-ir', ext: 'mach',
    description: 'Mach: linearized code with the activation record laid out (-dmach).',
  },
  {
    id: 'asm', label: 'Asm', language: 'gas', ext: 's',
    description: 'x86-64 assembly (-S).',
  },
  {
    id: 'rocq', label: 'Rocq AST', language: 'rocq', ext: 'v',
    description: 'The AST as a Rocq (Coq) term, as generated by clightgen.',
  },
];

export const VIEW_BY_ID = Object.fromEntries(VIEWS.map((v) => [v.id, v])) as Record<ViewId, View>;

/** RTL dumps, in the order of Compiler.transf_rtl_program. */
export const RTL_PASSES = [
  { name: 'RTL generation', short: 'initial', flag: null },
  { name: 'Tail calls', short: 'tailcall', flag: 'tailcalls' },
  { name: 'Inlining', short: 'inlining', flag: 'inline' },
  { name: 'Renumbering', short: 'renumber', flag: null },
  { name: 'Constant propagation', short: 'constprop', flag: 'const-prop' },
  { name: 'Renumbering', short: 'renumber', flag: 'const-prop' },
  { name: 'CSE', short: 'CSE', flag: 'cse' },
  { name: 'Redundancy elimination', short: 'deadcode', flag: 'redundancy' },
  { name: 'Unused globals', short: 'unusedglob', flag: null },
] as const;
